<template>
    <div>
        <div class="col-span-0"></div>
        <div class="col-span-1"></div>
        <div class="col-span-2"></div>
        <div class="col-span-3"></div>
        <div class="col-span-4"></div>
        <div class="col-span-5"></div>
        <div class="col-span-6"></div>
        <div class="col-span-7"></div>
        <div class="col-span-8"></div>
        <div class="col-span-9"></div>
        <div class="col-span-10"></div>
        <div class="col-span-11"></div>
        <div class="col-span-12"></div>
        <div class="bg-slate-50 text-slate-700"></div><div class="bg-slate-100 text-slate-800 "></div> <div class="bg-slate-200 text-slate-900"></div> <div class=" bg-slate-300"></div> <div class=" bg-slate-400 "></div> <div class="bg-slate-500 "></div> <div class="bg-slate-600 "></div> <div class="bg-slate-700 text-slate-950"></div> 
        <div class="bg-gray-50 text-gray-700"></div><div class="bg-gray-100 text-gray-800 "></div> <div class="bg-gray-200 text-gray-900"></div> <div class=" bg-gray-300"></div> <div class=" bg-gray-400 "></div> <div class="bg-gray-500 "></div> <div class="bg-gray-600 "></div> <div class="bg-gray-700 text-gray-950"></div> 
        <div class="bg-zinc-50 text-zinc-700"></div><div class="bg-zinc-100 text-zinc-800 "></div> <div class="bg-zinc-200 text-zinc-900"></div> <div class=" bg-zinc-300"></div> <div class=" bg-zinc-400 "></div> <div class="bg-zinc-500 "></div> <div class="bg-zinc-600 "></div> <div class="bg-zinc-700 text-zinc-950"></div> 
        <div class="bg-neutral-50 text-neutral-700"></div><div class="bg-neutral-100 text-neutral-800 "></div> <div class="bg-neutral-200 text-neutral-900"></div> <div class=" bg-neutral-300"></div> <div class=" bg-neutral-400 "></div> <div class="bg-neutral-500 "></div> <div class="bg-neutral-600 "></div> <div class="bg-neutral-700 text-neutral-950"></div> 
        <div class="bg-stone-50 text-stone-700"></div><div class="bg-stone-100 text-stone-800 "></div> <div class="bg-stone-200 text-stone-900"></div> <div class=" bg-stone-300"></div> <div class=" bg-stone-400 "></div> <div class="bg-stone-500 "></div> <div class="bg-stone-600 "></div> <div class="bg-stone-700 text-stone-950"></div> 
        <div class="bg-red-50 text-red-700"></div><div class="bg-red-100 text-red-800 "></div> <div class="bg-red-200 text-red-900"></div> <div class=" bg-red-300"></div> <div class=" bg-red-400 "></div> <div class="bg-red-500 "></div> <div class="bg-red-600 "></div> <div class="bg-red-700 text-red-950"></div> 
        <div class="bg-orange-50 text-orange-700"></div><div class="bg-orange-100 text-orange-800 "></div> <div class="bg-orange-200 text-orange-900"></div> <div class=" bg-orange-300"></div> <div class=" bg-orange-400 "></div> <div class="bg-orange-500 "></div> <div class="bg-orange-600 "></div> <div class="bg-orange-700 text-orange-950"></div> 
        <div class="bg-amber-50 text-amber-700"></div><div class="bg-amber-100 text-amber-800 "></div> <div class="bg-amber-200 text-amber-900"></div> <div class=" bg-amber-300"></div> <div class=" bg-amber-400 "></div> <div class="bg-amber-500 "></div> <div class="bg-amber-600 "></div> <div class="bg-amber-700 text-amber-950"></div> 
        <div class="bg-yellow-50 text-yellow-700"></div><div class="bg-yellow-100 text-yellow-800 "></div> <div class="bg-yellow-200 text-yellow-900"></div> <div class=" bg-yellow-300"></div> <div class=" bg-yellow-400 "></div> <div class="bg-yellow-500 "></div> <div class="bg-yellow-600 "></div> <div class="bg-yellow-700 text-yellow-950"></div> 
        <div class="bg-lime-50 text-lime-700"></div><div class="bg-lime-100 text-lime-800 "></div> <div class="bg-lime-200 text-lime-900"></div> <div class=" bg-lime-300"></div> <div class=" bg-lime-400 "></div> <div class="bg-lime-500 "></div> <div class="bg-lime-600 "></div> <div class="bg-lime-700 text-lime-950"></div> 
        <div class="bg-green-50 text-green-700"></div><div class="bg-green-100 text-green-800 "></div> <div class="bg-green-200 text-green-900"></div> <div class=" bg-green-300"></div> <div class=" bg-green-400 "></div> <div class="bg-green-500 "></div> <div class="bg-green-600 "></div> <div class="bg-green-700 text-green-950"></div> 
        <div class="bg-emerald-50 text-emerald-700"></div><div class="bg-emerald-100 text-emerald-800 "></div> <div class="bg-emerald-200 text-emerald-900"></div> <div class=" bg-emerald-300"></div> <div class=" bg-emerald-400 "></div> <div class="bg-emerald-500 "></div> <div class="bg-emerald-600 "></div> <div class="bg-emerald-700 text-emerald-950"></div> 
        <div class="bg-teal-50 text-teal-700"></div><div class="bg-teal-100 text-teal-800 "></div> <div class="bg-teal-200 text-teal-900"></div> <div class=" bg-teal-300"></div> <div class=" bg-teal-400 "></div> <div class="bg-teal-500 "></div> <div class="bg-teal-600 "></div> <div class="bg-teal-700 text-teal-950"></div> 
        <div class="bg-cyan-50 text-cyan-700"></div><div class="bg-cyan-100 text-cyan-800 "></div> <div class="bg-cyan-200 text-cyan-900"></div> <div class=" bg-cyan-300"></div> <div class=" bg-cyan-400 "></div> <div class="bg-cyan-500 "></div> <div class="bg-cyan-600 "></div> <div class="bg-cyan-700 text-cyan-950"></div> 
        <div class="bg-sky-50 text-sky-700"></div><div class="bg-sky-100 text-sky-800 "></div> <div class="bg-sky-200 text-sky-900"></div> <div class=" bg-sky-300"></div> <div class=" bg-sky-400 "></div> <div class="bg-sky-500 "></div> <div class="bg-sky-600 "></div> <div class="bg-sky-700 text-sky-950"></div> 
        <div class="bg-blue-50 text-blue-700"></div><div class="bg-blue-100 text-blue-800 "></div> <div class="bg-blue-200 text-blue-900"></div> <div class=" bg-blue-300"></div> <div class=" bg-blue-400 "></div> <div class="bg-blue-500 "></div> <div class="bg-blue-600 "></div> <div class="bg-blue-700 text-blue-950"></div> 
        <div class="bg-indigo-50 text-indigo-700"></div><div class="bg-indigo-100 text-indigo-800 "></div> <div class="bg-indigo-200 text-indigo-900"></div> <div class=" bg-indigo-300"></div> <div class=" bg-indigo-400 "></div> <div class="bg-indigo-500 "></div> <div class="bg-indigo-600 "></div> <div class="bg-indigo-700 text-indigo-950"></div> 
        <div class="bg-violet-50 text-violet-700"></div><div class="bg-violet-100 text-violet-800 "></div> <div class="bg-violet-200 text-violet-900"></div> <div class=" bg-violet-300"></div> <div class=" bg-violet-400 "></div> <div class="bg-violet-500 "></div> <div class="bg-violet-600 "></div> <div class="bg-violet-700 text-violet-950"></div> 
        <div class="bg-purple-50 text-purple-700"></div><div class="bg-purple-100 text-purple-800 "></div> <div class="bg-purple-200 text-purple-900"></div> <div class=" bg-purple-300"></div> <div class=" bg-purple-400 "></div> <div class="bg-purple-500 "></div> <div class="bg-purple-600 "></div> <div class="bg-purple-700 text-purple-950"></div> 
        <div class="bg-fuchsia-50 text-fuchsia-700"></div><div class="bg-fuchsia-100 text-fuchsia-800 "></div> <div class="bg-fuchsia-200 text-fuchsia-900"></div> <div class=" bg-fuchsia-300"></div> <div class=" bg-fuchsia-400 "></div> <div class="bg-fuchsia-500 "></div> <div class="bg-fuchsia-600 "></div> <div class="bg-fuchsia-700 text-fuchsia-950"></div> 
        <div class="bg-pink-50 text-pink-700"></div><div class="bg-pink-100 text-pink-800 "></div> <div class="bg-pink-200 text-pink-900"></div> <div class=" bg-pink-300"></div> <div class=" bg-pink-400 "></div> <div class="bg-pink-500 "></div> <div class="bg-pink-600 "></div> <div class="bg-pink-700 text-pink-950"></div> 
        <div class="bg-rose-50 text-rose-700"></div><div class="bg-rose-100 text-rose-800 "></div> <div class="bg-rose-200 text-rose-900"></div> <div class=" bg-rose-300"></div> <div class=" bg-rose-400 "></div> <div class="bg-rose-500 "></div> <div class="bg-rose-600 "></div> <div class="bg-rose-700 text-rose-950"></div> 

    </div>
</template>